title: The Measuring Type
description: I have made this blog to explore the way typography is used in diet
  products and programs as a method of influencing consumers to buy into the
  diet industry and diet culture, as a whole.
header_text: ""
footer_text: Copyright 2020 Your name
header_feature_image: ""
bannerheight: 20vmax
logo: ../uploads/the-measuring-type.png
favicon: ../uploads/the-measuring-type.png
gridlayout: false
fixednavbar: false
upzoom: true
